//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace задание_2_wpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int id { get; set; }
        public string nazvanie { get; set; }
        public Nullable<int> vid { get; set; }
    
        public virtual VidTovara VidTovara { get; set; }
    }
}
